'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { randomUUID } from 'crypto'
import { requireAdmin } from '@/lib/auth/require'
import { getAdminClient } from '@/lib/supabase/admin'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Brief {
  id: string
  title: string
  slug: string
  subtitle: string | null
  topic_tag: string | null
  pinned_media_post_id: string | null
  last_reviewed_at: string | null
  visibility: 'public' | 'members_only'
  created_at: string
  updated_at: string
}

export interface MediaPickerOption {
  id: string
  title: string
  post_type: 'video' | 'article' | 'paper' | 'resource'
}

export type BriefSectionType =
  | 'tldr'
  | 'use_this'
  | 'featured_news'
  | 'explainer'
  | 'where_experts_stand'
  | 'going_deeper'
  | 'faq'

export interface BriefSection {
  id: string
  brief_id: string
  section_type: BriefSectionType
  content: string
  display_order: number
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

export async function createBrief(): Promise<never> {
  await requireAdmin()

  const slug = `brief-${randomUUID()}`

  const { data: brief, error } = await getAdminClient()
    .from('briefs')
    .insert({ title: 'Untitled', slug, visibility: 'members_only' })
    .select('id')
    .single()

  if (error || !brief) throw new Error(error?.message ?? 'Failed to create brief')

  await getAdminClient().from('brief_sections').insert([
    { brief_id: brief.id, section_type: 'tldr',                 content: '', display_order: 1 },
    { brief_id: brief.id, section_type: 'use_this',              content: '', display_order: 2 },
    { brief_id: brief.id, section_type: 'featured_news',         content: '', display_order: 3 },
    { brief_id: brief.id, section_type: 'explainer',             content: '', display_order: 4 },
    { brief_id: brief.id, section_type: 'where_experts_stand',   content: '', display_order: 5 },
    { brief_id: brief.id, section_type: 'going_deeper',          content: '', display_order: 6 },
    { brief_id: brief.id, section_type: 'faq',                   content: '', display_order: 7 },
  ])

  redirect(`/admin/briefs/${brief.id}`)
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

export async function getBrief(id: string): Promise<{
  brief: Brief | null
  sections: BriefSection[]
  error: string | null
}> {
  await requireAdmin()

  const [briefResult, sectionsResult] = await Promise.all([
    getAdminClient().from('briefs').select('*').eq('id', id).single(),
    getAdminClient().from('brief_sections').select('*').eq('brief_id', id).order('display_order'),
  ])

  if (briefResult.error) return { brief: null, sections: [], error: briefResult.error.message }

  return {
    brief: briefResult.data as Brief,
    sections: (sectionsResult.data ?? []) as BriefSection[],
    error: null,
  }
}

// Non-quote posts, for the "pinned media" picker in the brief editor
// (design doc §2 row 8 — the pin must be a media item, not a quote).
export async function getMediaPickerOptions(): Promise<MediaPickerOption[]> {
  await requireAdmin()

  const { data } = await getAdminClient()
    .from('content_posts')
    .select('id, title, post_type')
    .neq('post_type', 'quote')
    .order('created_at', { ascending: false })
    .limit(200)

  return (data ?? []) as MediaPickerOption[]
}

// ---------------------------------------------------------------------------
// Slug helpers
// ---------------------------------------------------------------------------

// Placeholder slugs generated by createBrief look like brief-<uuid>
const PLACEHOLDER_SLUG = /^brief-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
}

async function uniqueSlug(base: string, briefId: string): Promise<string> {
  const candidate = base || `brief-${briefId.slice(0, 8)}`
  const { data } = await getAdminClient()
    .from('briefs')
    .select('slug')
    .like('slug', `${candidate}%`)
    .neq('id', briefId)

  const taken = new Set((data ?? []).map((r: { slug: string }) => r.slug))
  if (!taken.has(candidate)) return candidate
  for (let i = 2; ; i++) {
    if (!taken.has(`${candidate}-${i}`)) return `${candidate}-${i}`
  }
}

// ---------------------------------------------------------------------------
// Save
// ---------------------------------------------------------------------------

export async function saveBrief(
  briefId: string,
  data: {
    title: string
    subtitle: string
    topicTag: string
    pinnedMediaPostId: string | null
    visibility: 'public' | 'members_only'
    sections: Array<{ id: string; content: string; display_order: number }>
  }
): Promise<{ success?: boolean; error?: string }> {
  await requireAdmin()

  const updates: Record<string, unknown> = {
    title: data.title,
    subtitle: data.subtitle.trim() || null,
    topic_tag: data.topicTag.trim() || null,
    pinned_media_post_id: data.pinnedMediaPostId,
    visibility: data.visibility,
  }

  // Replace the placeholder slug with a title-derived one on the first save
  // with a real title. Established slugs never change — brief URLs are public.
  const { data: existing } = await getAdminClient()
    .from('briefs')
    .select('slug')
    .eq('id', briefId)
    .single()

  const title = data.title.trim()
  if (existing && PLACEHOLDER_SLUG.test(existing.slug) && title && title !== 'Untitled') {
    updates.slug = await uniqueSlug(slugify(title), briefId)
  }

  const { error: briefError } = await getAdminClient()
    .from('briefs')
    .update(updates)
    .eq('id', briefId)

  if (briefError) return { error: briefError.message }

  for (const section of data.sections) {
    const { error } = await getAdminClient()
      .from('brief_sections')
      .update({ content: section.content, display_order: section.display_order })
      .eq('id', section.id)

    if (error) return { error: error.message }
  }

  revalidatePath('/admin')
  revalidatePath(`/admin/briefs/${briefId}`)
  return { success: true }
}

// ---------------------------------------------------------------------------
// Delete
// ---------------------------------------------------------------------------

export async function deleteBrief(briefId: string): Promise<never> {
  await requireAdmin()

  await getAdminClient().from('briefs').delete().eq('id', briefId)
  redirect('/admin')
}
