'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { randomUUID } from 'crypto'
import { requireAdmin } from '@/lib/auth/require'
import { getAdminClient } from '@/lib/supabase/admin'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Brief {
  id: string
  title: string
  slug: string
  tldr: string
  visibility: 'public' | 'members_only'
  created_at: string
  updated_at: string
}

export interface BriefSection {
  id: string
  brief_id: string
  section_type: 'recent_developments' | 'sources_basic' | 'sources_advanced' | 'faq'
  content: string
  display_order: number
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

export async function createBrief(): Promise<never> {
  await requireAdmin()

  const slug = `brief-${randomUUID()}`

  const { data: brief, error } = await getAdminClient()
    .from('briefs')
    .insert({ title: 'Untitled', slug, tldr: '', visibility: 'members_only' })
    .select('id')
    .single()

  if (error || !brief) throw new Error(error?.message ?? 'Failed to create brief')

  await getAdminClient().from('brief_sections').insert([
    { brief_id: brief.id, section_type: 'recent_developments', content: '', display_order: 1 },
    { brief_id: brief.id, section_type: 'sources_basic',        content: '', display_order: 2 },
    { brief_id: brief.id, section_type: 'sources_advanced',     content: '', display_order: 3 },
    { brief_id: brief.id, section_type: 'faq',                  content: '', display_order: 4 },
  ])

  redirect(`/admin/briefs/${brief.id}`)
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

export async function getBrief(id: string): Promise<{
  brief: Brief | null
  sections: BriefSection[]
  error: string | null
}> {
  await requireAdmin()

  const [briefResult, sectionsResult] = await Promise.all([
    getAdminClient().from('briefs').select('*').eq('id', id).single(),
    getAdminClient().from('brief_sections').select('*').eq('brief_id', id).order('display_order'),
  ])

  if (briefResult.error) return { brief: null, sections: [], error: briefResult.error.message }

  return {
    brief: briefResult.data as Brief,
    sections: (sectionsResult.data ?? []) as BriefSection[],
    error: null,
  }
}

// ---------------------------------------------------------------------------
// Slug helpers
// ---------------------------------------------------------------------------

// Placeholder slugs generated by createBrief look like brief-<uuid>
const PLACEHOLDER_SLUG = /^brief-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
}

async function uniqueSlug(base: string, briefId: string): Promise<string> {
  const candidate = base || `brief-${briefId.slice(0, 8)}`
  const { data } = await getAdminClient()
    .from('briefs')
    .select('slug')
    .like('slug', `${candidate}%`)
    .neq('id', briefId)

  const taken = new Set((data ?? []).map((r: { slug: string }) => r.slug))
  if (!taken.has(candidate)) return candidate
  for (let i = 2; ; i++) {
    if (!taken.has(`${candidate}-${i}`)) return `${candidate}-${i}`
  }
}

// ---------------------------------------------------------------------------
// Save
// ---------------------------------------------------------------------------

export async function saveBrief(
  briefId: string,
  data: {
    title: string
    tldr: string
    visibility: 'public' | 'members_only'
    sections: Array<{ id: string; content: string; display_order: number }>
  }
): Promise<{ success?: boolean; error?: string }> {
  await requireAdmin()

  const updates: Record<string, unknown> = {
    title: data.title,
    tldr: data.tldr,
    visibility: data.visibility,
  }

  // Replace the placeholder slug with a title-derived one on the first save
  // with a real title. Established slugs never change — brief URLs are public.
  const { data: existing } = await getAdminClient()
    .from('briefs')
    .select('slug')
    .eq('id', briefId)
    .single()

  const title = data.title.trim()
  if (existing && PLACEHOLDER_SLUG.test(existing.slug) && title && title !== 'Untitled') {
    updates.slug = await uniqueSlug(slugify(title), briefId)
  }

  const { error: briefError } = await getAdminClient()
    .from('briefs')
    .update(updates)
    .eq('id', briefId)

  if (briefError) return { error: briefError.message }

  for (const section of data.sections) {
    const { error } = await getAdminClient()
      .from('brief_sections')
      .update({ content: section.content, display_order: section.display_order })
      .eq('id', section.id)

    if (error) return { error: error.message }
  }

  revalidatePath('/admin')
  revalidatePath(`/admin/briefs/${briefId}`)
  return { success: true }
}

// ---------------------------------------------------------------------------
// Delete
// ---------------------------------------------------------------------------

export async function deleteBrief(briefId: string): Promise<never> {
  await requireAdmin()

  await getAdminClient().from('briefs').delete().eq('id', briefId)
  redirect('/admin')
}
