import 'server-only'

import { getAdminClient } from '@/lib/supabase/admin'

// Split out of brief-actions.ts (Part 10) so lib/admin/actions.ts's
// convertProposalToBrief can reuse it too — a plain module, not a 'use
// server' one, since slugify is synchronous and a 'use server' file's
// exports must all be async Server Actions.

// Placeholder slugs generated by createBrief look like brief-<uuid>
export const PLACEHOLDER_SLUG = /^brief-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
}

export async function uniqueSlug(base: string, briefId: string): Promise<string> {
  const candidate = base || `brief-${briefId.slice(0, 8)}`
  const { data } = await getAdminClient()
    .from('briefs')
    .select('slug')
    .like('slug', `${candidate}%`)
    .neq('id', briefId)

  const taken = new Set((data ?? []).map((r: { slug: string }) => r.slug))
  if (!taken.has(candidate)) return candidate
  for (let i = 2; ; i++) {
    if (!taken.has(`${candidate}-${i}`)) return `${candidate}-${i}`
  }
}
